language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: "Un7mdUguaIjuOT6HZyVMRAdebJUh5FLVQ6T2JDljwFOUGCb9wjeoEI9FBjBJRQegvkAuJLm3Hym5Qh91bjAWRpSaiFr6+RuGUUG6WCtOHnzMNYsVSD3MmLckdnVCuNLoFAo5O7Qt09f0ZyBer7pUsxeMCyWhdIupIzaLyaW2x9xhaXE0zplhVOl2K+C3Fr/QUgZv2LG0JmyQB3cHATDPOkYWNah3bbNMgedNvdTY1CywXEkNyzVjo8g2iV/VivS0KnoSlqTtVugBc5Z0kZM8Z+yhIYhOxdaSoW88xHG4ymkcW0Gr3PgcloyaTXdh1yhxx3Cwlzm1A85mNqq97b4JVVhKIGN7JPHDw9pruQq4ZQ0qFdaUgC7abaz+X+R1tmqOTDiYAi/VzcLlrJKz0tdZVIz+9iroM2Ot/SasFPNqvhr5xVl1mAEd29p4mSZTNQqxf8WLY5IZmoEIugMbPUQ4aScJoBRbqvXEQRicWa64Qqz4nlP/XzrnbZqY0rH5bBgD2egyFtWfARx4MbEjtxWHHA4XeWwBjC1crcov20zv2WTtCqMslvEA/rTrHPYmF93atQbYtdvYY1dAbRzKdFsTgccuWiE2Wx/2teKPo7Y/FDe/sMl5as6ef38Y2i846PMWR/QLwAvtGnFZSj54sRAQJKKjMG2Tfo3JT/2u5PgmH4I="
  on:
    tags: true
    repo: scrapinghub/scrapy-autoextract
    condition: $TOXENV == py36
