language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: RLAvXglJ0mFwJu6SjgBWIxCVsLpRTorD/5wD8veUXqGha7U+5NT8et7U92GoW7UwYCpo8wXdQ4pm94zs8pH6aDr2O4geizk4a3twp02zsBOE3EG3CugEXKHdH0F4M0p8S7hIvVEwZ6JlnYzoQsaM1XYiBA2pmeD1KlkNZtnAVbD8pGe69Xvt9HY/6Qg0DoDahqOqNEh3l0/fU5RzKE0+LPaioXgIhm2AKdaekNV4wMQwECLcpcgaUVK0d6EDRv2/K+QQmMD1iI1xlbz0FZAjrcDL+8SRtOTT5PilfbcycGdtXo57MEJBzXH+fEXr6JQro5KhioCfQzEiggcQKNaor/w6xoiLzBzo06NABXwskK1cj8wY/A0kpCMgvn72jJdyXfq2EzNq7ItzVL8ZwcABQ+t1U99ECbaOibM7oK3r4uKz2BXTWZNAL9QiOWSlBw4J/kCAtZJr/lsbLKsPRmO+6I+Mz6yAsxY312yW49mFRcoT7Rv+Jr7eHDmBXcpNHsH94NLSh7JvLfsIYN4FJmoaMSXAOe2eOA48hp64frxZpWY/mNxHEFgxiPHy4C5uI63ouTN2Uhw9uLld9TdOmKPyG4J6d6K9YecyeQZtuoOuh3SF79iTzAIBbl6EXHwPHkok7lUpOMChjWtLUFE1TM0gvhHs5QsQrTq4ldAWZ+VZx7g=
  on:
    tags: true
    repo: scrapinghub/scrapy-autoextract
    condition: "$TOXENV == py37"
