language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJGUxZWEzMTg2LTNkOTgtNDkzYS05MzhhLTYxMTdkM2IxZTU3MgACQ3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzY3JhcHktYXV0b2V4dHJhY3QiXX0sICJ2ZXJzaW9uIjogMX0AAAYg5xt3O5fqZGr9jxes8C1z1cwTi7RHmFVV4Y3mxCSaxOQ"
  on:
    tags: true
    repo: scrapinghub/scrapy-autoextract
    condition: $TOXENV == py36
