language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox

deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  password:
    secure: "MP9odndlosr6IKO4LvlLvqNfdrOpFzdM3Y6I1gWUOnZbLjQ7ZG71wnZEpGrWi2vZh4slas970PaR5ctUwXT/UO+dmya8dhAQ2+8pvd7sZehgHOb0Pss/9aQjYpzrhta/tooec6E/Czq8gOKwK+m4ONMjVwfTBE8FdzRSWh7Iqz71RZgZQDCIvnahjBnjJh6Fm/uwQ9ZCokvB6w1I8RlGvVJ7aJSCevEWdHI8Z/cAs/FK5wQBqHXxYZhnQYsTwOmjkIOf+ULUi2gT5HqCznzlciYOam5GdBXh5eLEe2FzITwuQbHdJ0y4Nr3KtLRtcR1thmcsVqak7B22pwsNhqMzZShCHecbVvHS3v6zJ/p9hH2hXXELMiIjfSKw00uf1kw2KNMsXtHW5HH8lP0GoFIjPz+Cjxo6gAYQgU5FG4s8hSEupCEedgmN+nPQDkOO60mGYeHaOQ+1+aSSn3PShr7Cs++F1WkRzamREa4syGLN6RhOniKiszSaGCe/elm4W2hAcaXtxKU9+Jud6lmXBzKwfCf8SjWPCSNcpSJrFkfcYmT0CjeD81vsA+1DX7PxHDpXTfgrcqvUztQWvgbWfXZZOk8Yx4DDWrPOZGz9paAJrJwyzNPj4VN/x9/cTCAwU+v9WdQ02s5tJCKx0nOy+Ed73TRjsaKm+Uv82SIQmZOcqxY="
  on:
    tags: true
    repo: scrapinghub/scrapy-autoextract
    condition: $TOXENV == py36
