language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=flake8

# command to install dependencies
install: pip install -U tox

# command to run tests
script: tox

deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  password:
    secure: "l8yNbG0lk5G/rSZBtSdjprsHYuAkrwwT2pmy5qfcSzrObRxjnTwV2IHFLXbJygWOa7aN7unT7AQuoXBQhJItoYQD2TYj0Rh+DXypniKqp1zdTwqVcRxHb2DauM47IEQCveoo3miIpZtgrhKucjpLgx4JMJaTRw8s6mSeBOXG5ScGQ4RiIXGKOLzrG7WVWjG3FpkKcIDgL4FG5hi7OyFykZKmavR6LM2NRlsGoTIC2BW9OhD/Xj2RDPY5peXBhps2IGYNdvrqrMzEF0vqen543u1+6TGkAr1Yy18qDjdhp0IP+EViuVcS3zlv1gM7FbAvDclO4w36Bp+h3ykY28Px/7k/z3KPmfSV8GYJ23Ai+lKKyGnd2dJBZQClBZJDqF1fsHkaZye41bNYZsHa7lHn/Kz3pLy7s7u3NnnQuk0Z+GkZ/EdDyNnfjM1bTdShH3FXGoafCU8NDtgoOFbnSjEmQKg0cG7eRC/F0s6i2BRaihpy++Ki2uS+9qzIXRtoelDeYutt5xc/XhbFs527fipfAbR4VuMgZ2YtO+M97r2G2RYWAZnp5zxXMWzI9tSpJHH4uw9D4iaKoAngg0J4lvQrTlFB1saqo/oPSnXemOuWnXLLWxHKNdcPk/vjzekAYCJvS60t5qvf3FGv2vzT3CaG+7+MFEZLJq/vh+JkQFj2+lU="
  on:
    tags: true
    repo: scrapinghub/scrapy-autoextract
    condition: $TOXENV == py36
